const searchButton = document.querySelector (".search-btn")
const historyButtonContainer = document.querySelector (".history-btns")
const cityInput = document.querySelector (".city-input")
const currentWeatherDiv = document.querySelector (".current-weather")
const forcastCardDiv = document.querySelector (".forcast-cards")